version: '3.8'
services:
  mysql-slave:
    image: mysql
    container_name: mysql-slave
    restart: always
    env_file:
      - ./.env
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_SLAVE_PORT:3306
    command: >
      --server-id=$MYSQL_SLAVE_SERVER_ID
      --relay-log=mysql-relay-bin
      --log-bin=mysql-bin
      --read-only=1
    volumes:
      - ./mysql_slave_data:/var/lib/mysql
      - ../initdb:/docker-entrypoint-initdb.d 
volumes:
  mysql_slave_data: