#compose para mater

version: '3.8'
services:
  mysql-master:
    image: mysql:8
    container_name: mysql-master
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_MASTER_PORT}:3306"
    command: >
      --server-id=${MYSQL_MASTER_SERVER_ID}
      --log-bin=mysql-bin
      --binlog-do-db=cinestelar
      --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_master_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d  # Script de inicialización bd
volumes:
  mysql_master_data:
